"""Added repeat_type and custom_days to Chore model

Revision ID: 46321ec49350
Revises: 
Create Date: 2025-04-03 16:13:58.612002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46321ec49350'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('custom_days')
        batch_op.drop_column('repeat_type')

    # ### end Alembic commands ###
