"""Added calendar events and recurring expenses

Revision ID: 6281653ff7bd
Revises: b4df4f5bc4f6
Create Date: 2025-04-17 01:02:52.022923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6281653ff7bd'
down_revision = 'b4df4f5bc4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reminder', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_column('is_reminder')

    # ### end Alembic commands ###
