"""Add recurring fields to Expense

Revision ID: b4df4f5bc4f6
Revises: 8d6919e30abc
Create Date: 2025-04-15 17:29:55.986801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4df4f5bc4f6'
down_revision = '8d6919e30abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('next_due_date')
        batch_op.drop_column('recurrence_type')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
